const defaultAgents=[
{name:"Nova Sentinel",role:"Security & Monitoring",icon:"◈",status:"ONLINE",load:72,color:"cyan"},
{name:"Pixel Scout",role:"Game Analytics",icon:"◆",status:"ONLINE",load:48,color:"purple"},
{name:"Quest Runner",role:"Automation",icon:"⚡",status:"BUSY",load:91,color:"orange"},
{name:"Loot Analyst",role:"Recommendation AI",icon:"◉",status:"ONLINE",load:35,color:"green"},
{name:"Brief Bot",role:"Report Generation",icon:"✦",status:"ONLINE",load:41,color:"cyan"},
{name:"Arena Coach",role:"Strategy Intelligence",icon:"♜",status:"BUSY",load:67,color:"purple"},
{name:"Patch Watcher",role:"Game Updates",icon:"⌁",status:"ONLINE",load:29,color:"green"},
{name:"Risk Hunter",role:"Fraud Detection",icon:"⚠",status:"OFFLINE",load:0,color:"orange"}
];

const state={
 agents:JSON.parse(localStorage.getItem("agentx_agents")||"null")||defaultAgents,
 tasks:JSON.parse(localStorage.getItem("agentx_tasks")||"null")||[],
 xp:Number(localStorage.getItem("agentx_xp")||8420),
 theme:localStorage.getItem("agentx_theme")||"neon"
};
function save(){localStorage.setItem("agentx_agents",JSON.stringify(state.agents));localStorage.setItem("agentx_tasks",JSON.stringify(state.tasks));localStorage.setItem("agentx_xp",state.xp)}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(msg,type="success"){let t=document.querySelector(".toast");if(!t){t=document.createElement("div");t.className="toast";document.body.appendChild(t)}t.textContent=(type==="error"?"⚠ ":"✓ ")+msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2200)}
function setActiveNav(){const file=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".sidebar nav a").forEach(a=>{a.classList.toggle("active",a.getAttribute("href")===file)})}
function renderSidebar(){document.querySelectorAll(".sidebar").forEach(s=>{if(!s.innerHTML.trim())s.innerHTML=`<div class="brand"><span class="brand-orb">✦</span><div>AGENT<span>X</span><small>GAMER COMMAND CENTER</small></div></div><nav><a href="index.html">⌂ <span>Dashboard</span></a><a href="agents.html">◈ <span>AI Agents</span><b id="agentCount">${state.agents.length}</b></a><a href="tasks.html">▣ <span>Task Queue</span><b id="taskCount">${state.tasks.length||7}</b></a><a href="workflows.html">⌘ <span>Workflows</span></a><a href="activity.html">◉ <span>Activity Log</span></a><a href="history.html">◷ <span>Execution History</span></a><a href="builder.html">✚ <span>Agent Builder</span></a></nav><div class="side-card"><div class="mini-label">PLAYER</div><strong>SANDEEP</strong><div class="xp"><i style="width:${Math.min(100,state.xp/100)}%"></i></div><small>LVL ${Math.floor(state.xp/350)+1} • ${state.xp.toLocaleString()} XP</small></div><a class="settings" href="settings.html">⚙ Settings</a>`});setActiveNav()}
function initBars(){const bars=document.getElementById("bars");if(!bars)return;changeChart("Last 7 Days")}
function changeChart(v){const bars=document.getElementById("bars");if(!bars)return;const sets={"Last 7 Days":[58,72,49,82,65,91,76],"Last 30 Days":[42,66,53,78,61,84,70,88,73,92,69,81],"Today":[30,48,41,67,55,73,64]};const vals=sets[v]||sets["Last 7 Days"];bars.innerHTML=vals.map((n,i)=>`<div class="bar-col"><div class="bar" style="height:${n}%"></div><small>${v==="Today"?`${i+1}h`:v==="Last 30 Days"?`${i+1}`:["M","T","W","T","F","S","S"][i]}</small></div>`).join("");toast("Chart updated: "+v)}
function renderAgents(list=state.agents){const grid=document.getElementById("agentGrid");if(!grid)return;grid.innerHTML=list.length?list.map((a,i)=>`<article class="agent-card"><div class="agent-top"><div class="agent-icon ${esc(a.color)}">${esc(a.icon)}</div><span class="status-text ${a.status.toLowerCase()}"><i></i>${a.status}</span></div><h2>${esc(a.name)}</h2><p>${esc(a.role)}</p><div class="card-line"></div><div class="agent-meta"><span>LOAD <b>${a.load}%</b></span><span>HEALTH <b>${a.status==="OFFLINE"?"—":"99%"}</b></span></div><div class="load"><i style="width:${a.load}%"></i></div><button onclick="viewAgent(${i})">VIEW PROFILE →</button></article>`).join(""):`<div class="panel" style="grid-column:1/-1;text-align:center;padding:40px">No agents found.</div>`}
function filterAgents(){const q=(document.getElementById("agentSearch")?.value||"").toLowerCase();const active=document.querySelector(".filter.active")?.textContent.trim();renderAgents(state.agents.filter(a=>(!q||a.name.toLowerCase().includes(q)||a.role.toLowerCase().includes(q))&&(active==="ALL"||!active||a.status===active)))}
function setupFilters(){document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{const group=b.closest(".filterbar,.activity-filter");if(group){group.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(document.getElementById("agentGrid"))filterAgents()}}))}
function viewAgent(i){const a=state.agents[i];if(a)toast(`${a.name} • ${a.status} • Load ${a.load}%`)}
function addTask(){const row=document.getElementById("taskRows");if(!row){toast("Task queue is unavailable","error");return}const id="#AX-"+(1043+row.children.length);const tr=document.createElement("tr");tr.dataset.taskId=id;tr.innerHTML=`<td>${id}</td><td><b>New Sandeep mission</b><small>Created from command center</small></td><td>Nova Sentinel</td><td><label class="high">HIGH</label></td><td><span class="pill queued">QUEUED</span></td><td><div class="table-progress"><i style="width:3%"></i></div></td><td><button class="smallbtn" onclick="startTask(this)">START</button></td>`;row.prepend(tr);state.tasks.push({id,name:"New Sandeep mission",status:"QUEUED"});save();toast("New task added")}
function startTask(btn){const tr=btn.closest("tr");const pill=tr.querySelector(".pill");const bar=tr.querySelector(".table-progress i");pill.className="pill running";pill.textContent="RUNNING";bar.style.width="55%";btn.textContent="PAUSE";btn.onclick=()=>pauseTask(btn);toast("Task started")}
function pauseTask(btn){const tr=btn.closest("tr");const pill=tr.querySelector(".pill");pill.className="pill queued";pill.textContent="PAUSED";btn.textContent="START";btn.onclick=()=>startTask(btn);toast("Task paused")}
function addNode(type){const canvas=document.querySelector(".canvas");if(!canvas){toast("Workflow canvas unavailable","error");return}const node=document.createElement("div");node.className="node";node.style.left=(10+Math.random()*65)+"%";node.style.top=(70+Math.random()*380)+"px";node.innerHTML=`<small>${esc(type.toUpperCase())}</small><b>${type==="AI Agent"?"◈ Nova Sentinel":type==="Trigger"?"⚡ New Trigger":type==="Decision"?"◆ Smart Decision":type==="Approval"?"✓ Human Approval":"↗ Execute Action"}</b><span>New workflow block</span>`;canvas.appendChild(node);toast(type+" block added")}
function testWorkflow(){toast("Test execution started");setTimeout(()=>toast("Workflow test completed successfully"),1400)}
function saveWorkflow(){toast("Workflow saved to local storage")}
function createAgent(){const name=document.getElementById("newName")?.value.trim()||"Sandeep Agent";const role=document.querySelector(".form-panel select")?.value||"AI Agent";state.agents.push({name,role,icon:"✦",status:"ONLINE",load:5,color:"cyan"});state.xp+=100;save();toast(`${name} deployed successfully`);setTimeout(()=>location.href="agents.html",600)}
function toggleSide(){document.querySelector(".sidebar")?.classList.toggle("open")}
function saveSettings(){const name=document.querySelector('.setting input')?.value.trim()||"Sandeep";localStorage.setItem("agentx_player",name);toast("Settings saved successfully")}
function updateClock(){document.querySelectorAll(".live").forEach(x=>{if(!x.dataset.base)x.dataset.base=x.textContent.trim();});const el=document.querySelector(".clock");if(el)el.textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}
document.addEventListener("mousemove",e=>{const g=document.querySelector(".cursor-glow");if(g){g.style.left=e.clientX+"px";g.style.top=e.clientY+"px"}});
document.addEventListener("DOMContentLoaded",()=>{renderSidebar();initBars();renderAgents();setupFilters();updateClock();setInterval(updateClock,1000);const input=document.getElementById("newName");if(input)input.addEventListener("input",()=>{const p=document.getElementById("previewName");if(p)p.textContent=input.value||"Unnamed Agent"});document.querySelectorAll(".filterbar .filter").forEach(b=>b.addEventListener("click",filterAgents));});
window.notify=toast;window.changeChart=changeChart;window.filterAgents=filterAgents;window.addTask=addTask;window.startTask=startTask;window.pauseTask=pauseTask;window.addNode=addNode;window.testWorkflow=testWorkflow;window.saveWorkflow=saveWorkflow;window.createAgent=createAgent;window.toggleSide=toggleSide;window.saveSettings=saveSettings;window.viewAgent=viewAgent;
